---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickerapi
  labels:
    app: clickerapi
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: clickerapi
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: clickerapi
    spec:
      containers:
      - name: clickerapi
        image: cr.yandex/crp23jo6ast7c3gqqdtn/clickerapi:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        envFrom:
        - configMapRef:
            name: clickerapi-env
      terminationGracePeriodSeconds: 180