---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-server
  labels:
    app: pg-server
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: pg-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pg-server
    spec:
      containers:
      - name: pg-server
        image: docker.io/library/postgres:17.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: tcp
          containerPort: 5432
        envFrom:
        - configMapRef:
            name: pg-server-env
      terminationGracePeriodSeconds: 180